apiVersion: v1
kind: Pod
metadata:
  name: busyboxplus
  namespace: todoapp
spec:
  containers:
    - name: busyboxplus
      image: ikulyk404/busyboxplus:curl
      args:
      - sleep
      - "3600"
    